spring:
  datasource:
    url: jdbc:h2:file:/app/db/data;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
hoaxify:
  upload-path: /app/static
